# Generated by Django 5.2.6 on 2025-10-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalllmproviderconfig',
            name='use_multi_agent',
            field=models.BooleanField(default=False, help_text='Usa sistema de múltiplos agentes especializados (Aline Atendimento + Aline Agenda)', verbose_name='Sistema Multi-Agent'),
        ),
        migrations.AddField(
            model_name='llmproviderconfig',
            name='use_multi_agent',
            field=models.BooleanField(default=False, help_text='Usa sistema de múltiplos agentes especializados (Aline Atendimento + Aline Agenda)', verbose_name='Sistema Multi-Agent'),
        ),
        migrations.AlterField(
            model_name='historicalllmproviderconfig',
            name='has_calendar_tools',
            field=models.BooleanField(default=False, help_text='Habilita integração com Google Calendar', verbose_name='Ferramentas de Calendário'),
        ),
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='has_calendar_tools',
            field=models.BooleanField(default=False, help_text='Habilita integração com Google Calendar', verbose_name='Ferramentas de Calendário'),
        ),
    ]
