# Generated by Django 5.2.6 on 2025-10-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_historicalllmproviderconfig_use_multi_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalllmproviderconfig',
            name='use_multi_agent',
        ),
        migrations.RemoveField(
            model_name='llmproviderconfig',
            name='use_multi_agent',
        ),
    ]
