# Generated by Django 5.2.6 on 2025-10-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_agentdocument_agentfile_conversation_and_more'),
        ('whatsapp_connector', '0003_alter_evolutioninstance_llm_config_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LLMProviderConfig',
        ),
        migrations.AddIndex(
            model_name='longtermmemory',
            index=models.Index(fields=['contact'], name='agents_long_contact_777a1c_idx'),
        ),
    ]
