# Generated by Django 5.2.6 on 2025-10-24 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_alter_agent_options_alter_agentfile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longtermmemory',
            name='source',
        ),
        migrations.AddField(
            model_name='longtermmemory',
            name='conversation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='agents.conversation'),
            preserve_default=False,
        ),
    ]
