# Generated by Django 5.2.6 on 2025-10-25 12:56

import agents.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
import uuid


def generate_unique_message_ids(apps, schema_editor):
    """Populate message_id with unique UUIDs for existing records"""
    Message = apps.get_model('agents', 'Message')
    # Use order_by('id') to override the default ordering which might use fields that don't exist yet
    # Generate new UUIDs for ALL existing messages to ensure uniqueness
    for message in Message.objects.order_by('id'):
        message.message_id = str(uuid.uuid4())
        message.save(update_fields=['message_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_remove_longtermmemory_source_and_more'),
        ('core', '0007_alter_contact_phone_number'),
        ('whatsapp_connector', '0005_alter_evolutioninstance_agent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-id'], 'verbose_name': 'Conversação', 'verbose_name_plural': 'Conversações'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-received_at'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact_summary',
            field=models.TextField(blank=True, help_text='Resumo das informações importantes sobre este contato, atualizado pela IA', null=True, verbose_name='Resumo do contato'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='evolution_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='whatsapp_connector.evolutioninstance', verbose_name='Instância Evolution'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_transcription',
            field=models.TextField(blank=True, null=True, verbose_name='Transcrição de Áudio'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='whatsapp_media/', verbose_name='Arquivo de Mídia'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Mídia'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(default=agents.models.generate_unique_message_id, max_length=255, verbose_name='ID da Mensagem'),
        ),
        migrations.RunPython(generate_unique_message_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default=agents.models.generate_unique_message_id, max_length=255, unique=True, verbose_name='ID da Mensagem'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('extended_text', 'Extended Text')], default='text', max_length=20, verbose_name='Tipo de Mensagem'),
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='message',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status de Processamento'),
        ),
        migrations.AddField(
            model_name='message',
            name='raw_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados Brutos'),
        ),
        migrations.AddField(
            model_name='message',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Recebido em'),
        ),
        migrations.AddField(
            model_name='message',
            name='received_while_inactive',
            field=models.BooleanField(default=False, help_text='Indica se a mensagem foi recebida enquanto a instância estava inativa', verbose_name='Recebida com instância inativa'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Remetente'),
        ),
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fonte'),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem do usuário'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
