# Generated by Django 5.2.6 on 2025-10-27 16:24

import agents.models
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Documento do Agente', 'verbose_name_plural': 'Documentos dos Agentes'},
        ),
        migrations.AlterModelOptions(
            name='conversationsummary',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Resumo de Conversação', 'verbose_name_plural': 'Resumos de Conversações'},
        ),
        migrations.AlterModelOptions(
            name='longtermmemory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Memória de Longo Prazo', 'verbose_name_plural': 'Memórias de Longo Prazo'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='frequency_penalty',
            field=models.FloatField(default=0.0, help_text='Penaliza tokens repetidos para reduzir repetição de frases', verbose_name='Penalidade de frequência'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='max_tokens',
            field=models.PositiveIntegerField(default=1024, help_text='Número máximo de tokens na resposta gerada', verbose_name='Máximo de tokens'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google DeepMind'), ('mistral', 'Mistral AI'), ('cohere', 'Cohere'), ('meta', 'Meta (LLaMA)'), ('xai', 'xAI (Grok)'), ('other', 'Outro')], default='openai', help_text='Provedor do modelo de linguagem (OpenAI, Anthropic, Google, etc.)', max_length=50, verbose_name='Fornecedor LLM'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='presence_penalty',
            field=models.FloatField(default=0.0, help_text='Penaliza tokens já mencionados para aumentar diversidade de tópicos', verbose_name='Penalidade de presença'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='temperature',
            field=models.FloatField(default=0.7, help_text='Controla a aleatoriedade das respostas (0.0 = determinístico, 1.0 = criativo)', verbose_name='Temperatura'),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='agent',
            field=models.ForeignKey(help_text='Agente ao qual este documento pertence', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agents.agent', verbose_name='Agente'),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='content',
            field=models.TextField(help_text='Texto do documento para busca semântica', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, help_text='Representação vetorial do conteúdo para busca semântica', verbose_name='Vetor de embedding'),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Informações adicionais sobre o documento', verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='agentfile',
            name='error_message',
            field=models.TextField(blank=True, help_text='Descrição do erro caso o processamento falhe', null=True, verbose_name='Mensagem de erro'),
        ),
        migrations.AlterField(
            model_name='agentfile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Tamanho do arquivo em bytes', null=True, verbose_name='Tamanho do arquivo (bytes)'),
        ),
        migrations.AlterField(
            model_name='agentfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Texto'), ('docx', 'Word'), ('md', 'Markdown'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML'), ('jpg', 'Imagem JPEG'), ('png', 'Imagem PNG'), ('gif', 'Imagem GIF'), ('webp', 'Imagem WEBP')], help_text='Formato do arquivo (PDF, texto, imagem, etc.)', max_length=10, verbose_name='Tipo do arquivo'),
        ),
        migrations.AlterField(
            model_name='agentfile',
            name='status',
            field=models.CharField(choices=[('uploading', 'Enviando'), ('processing', 'Processando'), ('ready', 'Pronto'), ('error', 'Erro')], default='uploading', help_text='Status atual do processamento do arquivo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='agentfile',
            name='vectorized',
            field=models.BooleanField(default=False, help_text='Indica se o arquivo já foi processado para busca vetorial', verbose_name='Vetorizado'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='from_number',
            field=models.CharField(help_text='Número do WhatsApp que iniciou a conversa', max_length=50, verbose_name='Número de origem'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('ai', 'Atendimento por IA'), ('human', 'Atendimento humano'), ('closed', 'Encerrada')], default='ai', help_text='Define se a conversa é atendida por IA, humano ou está encerrada', max_length=20, verbose_name='Status da sessão'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='to_number',
            field=models.CharField(help_text='Número do WhatsApp que recebe as mensagens', max_length=50, verbose_name='Número de destino'),
        ),
        migrations.AlterField(
            model_name='conversationsummary',
            name='conversation',
            field=models.OneToOneField(help_text='Conversação associada a este resumo', on_delete=django.db.models.deletion.CASCADE, to='agents.conversation', verbose_name='Conversação'),
        ),
        migrations.AlterField(
            model_name='conversationsummary',
            name='summary',
            field=models.TextField(help_text='Resumo automático da conversação gerado pela IA', verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='conversationsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='frequency_penalty',
            field=models.FloatField(default=0.0, help_text='Penaliza tokens repetidos para reduzir repetição de frases', verbose_name='Penalidade de frequência'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='max_tokens',
            field=models.PositiveIntegerField(default=1024, help_text='Número máximo de tokens na resposta gerada', verbose_name='Máximo de tokens'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='name',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google DeepMind'), ('mistral', 'Mistral AI'), ('cohere', 'Cohere'), ('meta', 'Meta (LLaMA)'), ('xai', 'xAI (Grok)'), ('other', 'Outro')], default='openai', help_text='Provedor do modelo de linguagem (OpenAI, Anthropic, Google, etc.)', max_length=50, verbose_name='Fornecedor LLM'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='presence_penalty',
            field=models.FloatField(default=0.0, help_text='Penaliza tokens já mencionados para aumentar diversidade de tópicos', verbose_name='Penalidade de presença'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='temperature',
            field=models.FloatField(default=0.7, help_text='Controla a aleatoriedade das respostas (0.0 = determinístico, 1.0 = criativo)', verbose_name='Temperatura'),
        ),
        migrations.AlterField(
            model_name='historicalagentfile',
            name='error_message',
            field=models.TextField(blank=True, help_text='Descrição do erro caso o processamento falhe', null=True, verbose_name='Mensagem de erro'),
        ),
        migrations.AlterField(
            model_name='historicalagentfile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Tamanho do arquivo em bytes', null=True, verbose_name='Tamanho do arquivo (bytes)'),
        ),
        migrations.AlterField(
            model_name='historicalagentfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Texto'), ('docx', 'Word'), ('md', 'Markdown'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML'), ('jpg', 'Imagem JPEG'), ('png', 'Imagem PNG'), ('gif', 'Imagem GIF'), ('webp', 'Imagem WEBP')], help_text='Formato do arquivo (PDF, texto, imagem, etc.)', max_length=10, verbose_name='Tipo do arquivo'),
        ),
        migrations.AlterField(
            model_name='historicalagentfile',
            name='status',
            field=models.CharField(choices=[('uploading', 'Enviando'), ('processing', 'Processando'), ('ready', 'Pronto'), ('error', 'Erro')], default='uploading', help_text='Status atual do processamento do arquivo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalagentfile',
            name='vectorized',
            field=models.BooleanField(default=False, help_text='Indica se o arquivo já foi processado para busca vetorial', verbose_name='Vetorizado'),
        ),
        migrations.AlterField(
            model_name='longtermmemory',
            name='content',
            field=models.TextField(help_text='Informações importantes extraídas da conversação', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='longtermmemory',
            name='conversation',
            field=models.OneToOneField(help_text='Conversação da qual esta memória foi extraída', on_delete=django.db.models.deletion.CASCADE, to='agents.conversation', verbose_name='Conversação'),
        ),
        migrations.AlterField(
            model_name='longtermmemory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='longtermmemory',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, help_text='Representação vetorial para busca semântica', verbose_name='Vetor de embedding'),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio_transcription',
            field=models.TextField(blank=True, help_text='Texto transcrito de mensagens de áudio via Deepgram', null=True, verbose_name='Transcrição de Áudio'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, help_text='Conteúdo textual da mensagem recebida', null=True, verbose_name='Mensagem do usuário'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL do arquivo de mídia (imagem, áudio, vídeo, documento)', null=True, verbose_name='URL da Mídia'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default=agents.models.generate_unique_message_id, help_text='Identificador único da mensagem', max_length=255, unique=True, verbose_name='ID da Mensagem'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('extended_text', 'Extended Text')], default='text', help_text='Tipo de conteúdo da mensagem (texto, áudio, imagem, etc.)', max_length=20, verbose_name='Tipo de Mensagem'),
        ),
        migrations.AlterField(
            model_name='message',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status do processamento da mensagem pelo sistema', max_length=20, verbose_name='Status de Processamento'),
        ),
        migrations.AlterField(
            model_name='message',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Dados originais do webhook da Evolution API', null=True, verbose_name='Dados Brutos'),
        ),
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.TextField(blank=True, help_text='Resposta gerada pelo agente de IA', null=True, verbose_name='Resposta da IA'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Nome do usuário que enviou a mensagem', max_length=255, null=True, verbose_name='Nome do Remetente'),
        ),
        migrations.AlterField(
            model_name='message',
            name='source',
            field=models.CharField(blank=True, help_text='Origem da mensagem (iOS, Android, Web, etc.)', max_length=50, null=True, verbose_name='Fonte'),
        ),
    ]
