# Generated by Django 5.2.6 on 2025-10-27 16:26

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_alter_agentdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdocument',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='conversationsummary',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agents.conversation'),
        ),
        migrations.AlterField(
            model_name='conversationsummary',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='conversationsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='longtermmemory',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='longtermmemory',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agents.conversation'),
        ),
        migrations.AlterField(
            model_name='longtermmemory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='longtermmemory',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
