# Generated by Django 5.2.6 on 2025-10-27 16:28

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_alter_agentdocument_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdocument',
            name='agent',
            field=models.ForeignKey(help_text='Agente ao qual este documento pertence', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='content',
            field=models.TextField(help_text='Texto do documento para busca semântica'),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do documento'),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, help_text='Representação vetorial do conteúdo para busca semântica'),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Informações adicionais sobre o documento'),
        ),
        migrations.AlterField(
            model_name='conversationsummary',
            name='conversation',
            field=models.OneToOneField(help_text='Conversação associada a este resumo', on_delete=django.db.models.deletion.CASCADE, to='agents.conversation'),
        ),
        migrations.AlterField(
            model_name='conversationsummary',
            name='summary',
            field=models.TextField(help_text='Resumo automático da conversação gerado pela IA'),
        ),
        migrations.AlterField(
            model_name='conversationsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do resumo'),
        ),
        migrations.AlterField(
            model_name='longtermmemory',
            name='content',
            field=models.TextField(help_text='Informações importantes extraídas da conversação'),
        ),
        migrations.AlterField(
            model_name='longtermmemory',
            name='conversation',
            field=models.OneToOneField(help_text='Conversação da qual esta memória foi extraída', on_delete=django.db.models.deletion.CASCADE, to='agents.conversation'),
        ),
        migrations.AlterField(
            model_name='longtermmemory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação da memória'),
        ),
        migrations.AlterField(
            model_name='longtermmemory',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, help_text='Representação vetorial para busca semântica'),
        ),
    ]
