# Generated by Django 5.2.6 on 2025-11-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_alter_agentdocument_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(blank=True, help_text='Define quem é o assistente, sua identidade, expertise e personalidade', null=True, verbose_name='Role (Papel)')),
                ('available_tools', models.TextField(blank=True, help_text='Lista e descrição das ferramentas e recursos que o assistente pode utilizar', null=True, verbose_name='Ferramentas Disponíveis')),
                ('input_context', models.TextField(blank=True, help_text='Como o assistente deve interpretar e processar as entradas do usuário', null=True, verbose_name='Input (Entrada/Contexto)')),
                ('steps', models.TextField(blank=True, help_text='Passo a passo de como o assistente deve processar e responder às solicitações', null=True, verbose_name='Steps (Passos)')),
                ('expectation', models.TextField(blank=True, help_text='O que se espera do assistente: formato de respostas, tom, estrutura', null=True, verbose_name='Expectation (Expectativa)')),
                ('anti_hallucination_policies', models.TextField(blank=True, help_text='Regras para evitar alucinações, limites do que o assistente pode/não pode fazer', null=True, verbose_name='Políticas Anti-Alucinação e Limites')),
                ('applied_example', models.TextField(blank=True, help_text='Exemplos práticos de interações e respostas esperadas', null=True, verbose_name='Exemplo Aplicado')),
                ('useful_default_messages', models.TextField(blank=True, help_text='Mensagens pré-definidas para situações comuns (saudações, despedidas, transferências)', null=True, verbose_name='Mensagens Padrão Úteis')),
                ('global_system_prompt', models.TextField(blank=True, help_text='Campo legado. Use os campos RISE acima.', null=True, verbose_name='[LEGADO] Prompt Global do Sistema')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Global',
                'verbose_name_plural': 'Configurações Globais',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='anti_hallucination_policies',
            field=models.TextField(blank=True, help_text='Regras para evitar alucinações, limites do que o assistente pode/não pode fazer', null=True, verbose_name='Políticas Anti-Alucinação e Limites'),
        ),
        migrations.AddField(
            model_name='agent',
            name='applied_example',
            field=models.TextField(blank=True, help_text='Exemplos práticos de interações e respostas esperadas', null=True, verbose_name='Exemplo Aplicado'),
        ),
        migrations.AddField(
            model_name='agent',
            name='available_tools',
            field=models.TextField(blank=True, help_text='Lista e descrição das ferramentas e recursos que o assistente pode utilizar', null=True, verbose_name='Ferramentas Disponíveis'),
        ),
        migrations.AddField(
            model_name='agent',
            name='expectation',
            field=models.TextField(blank=True, help_text='O que se espera do assistente: formato de respostas, tom, estrutura', null=True, verbose_name='Expectation (Expectativa)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='input_context',
            field=models.TextField(blank=True, help_text='Como o assistente deve interpretar e processar as entradas do usuário', null=True, verbose_name='Input (Entrada/Contexto)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.TextField(blank=True, help_text='Define quem é o assistente, sua identidade, expertise e personalidade', null=True, verbose_name='Role (Papel)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='steps',
            field=models.TextField(blank=True, help_text='Passo a passo de como o assistente deve processar e responder às solicitações', null=True, verbose_name='Steps (Passos)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='useful_default_messages',
            field=models.TextField(blank=True, help_text='Mensagens pré-definidas para situações comuns (saudações, despedidas, transferências)', null=True, verbose_name='Mensagens Padrão Úteis'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='anti_hallucination_policies',
            field=models.TextField(blank=True, help_text='Regras para evitar alucinações, limites do que o assistente pode/não pode fazer', null=True, verbose_name='Políticas Anti-Alucinação e Limites'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='applied_example',
            field=models.TextField(blank=True, help_text='Exemplos práticos de interações e respostas esperadas', null=True, verbose_name='Exemplo Aplicado'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='available_tools',
            field=models.TextField(blank=True, help_text='Lista e descrição das ferramentas e recursos que o assistente pode utilizar', null=True, verbose_name='Ferramentas Disponíveis'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='expectation',
            field=models.TextField(blank=True, help_text='O que se espera do assistente: formato de respostas, tom, estrutura', null=True, verbose_name='Expectation (Expectativa)'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='input_context',
            field=models.TextField(blank=True, help_text='Como o assistente deve interpretar e processar as entradas do usuário', null=True, verbose_name='Input (Entrada/Contexto)'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='role',
            field=models.TextField(blank=True, help_text='Define quem é o assistente, sua identidade, expertise e personalidade', null=True, verbose_name='Role (Papel)'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='steps',
            field=models.TextField(blank=True, help_text='Passo a passo de como o assistente deve processar e responder às solicitações', null=True, verbose_name='Steps (Passos)'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='useful_default_messages',
            field=models.TextField(blank=True, help_text='Mensagens pré-definidas para situações comuns (saudações, despedidas, transferências)', null=True, verbose_name='Mensagens Padrão Úteis'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='frequency_penalty',
            field=models.FloatField(default=0.0, verbose_name='Penalidade de frequência'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='max_tokens',
            field=models.PositiveIntegerField(default=1024, verbose_name='Máximo de tokens'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google DeepMind'), ('mistral', 'Mistral AI'), ('cohere', 'Cohere'), ('meta', 'Meta (LLaMA)'), ('xai', 'xAI (Grok)'), ('other', 'Outro')], default='openai', max_length=50, verbose_name='Fornecedor LLM'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='presence_penalty',
            field=models.FloatField(default=0.0, verbose_name='Penalidade de presença'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Prompt inicial ou system message (campo legado)', null=True, verbose_name='Instruções do agente'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='temperature',
            field=models.FloatField(default=0.7, verbose_name='Temperatura'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='frequency_penalty',
            field=models.FloatField(default=0.0, verbose_name='Penalidade de frequência'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='max_tokens',
            field=models.PositiveIntegerField(default=1024, verbose_name='Máximo de tokens'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='name',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google DeepMind'), ('mistral', 'Mistral AI'), ('cohere', 'Cohere'), ('meta', 'Meta (LLaMA)'), ('xai', 'xAI (Grok)'), ('other', 'Outro')], default='openai', max_length=50, verbose_name='Fornecedor LLM'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='presence_penalty',
            field=models.FloatField(default=0.0, verbose_name='Penalidade de presença'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Prompt inicial ou system message (campo legado)', null=True, verbose_name='Instruções do agente'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='temperature',
            field=models.FloatField(default=0.7, verbose_name='Temperatura'),
        ),
    ]
