# Generated by Django 5.2.6 on 2025-11-27 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_globalsettings_agent_anti_hallucination_policies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangchainCollection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cmetadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Coleção',
                'verbose_name_plural': 'Coleções',
                'db_table': 'langchain_pg_collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LangchainEmbedding',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('document', models.TextField(blank=True, null=True)),
                ('cmetadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Documento Vetorizado',
                'verbose_name_plural': 'Documentos Vetorizados',
                'db_table': 'langchain_pg_embedding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('provider', models.CharField(help_text='Ex: openai, anthropic, google', max_length=50, verbose_name='Provedor')),
                ('model_name', models.CharField(help_text='Ex: gpt-4o, claude-3-5-sonnet-20241022', max_length=100, verbose_name='Modelo')),
                ('input_tokens', models.IntegerField(default=0, help_text='Tokens enviados (prompt + contexto)', verbose_name='Tokens de Entrada')),
                ('output_tokens', models.IntegerField(default=0, help_text='Tokens gerados na resposta', verbose_name='Tokens de Saída')),
                ('total_tokens', models.IntegerField(default=0, help_text='Soma de entrada + saída', verbose_name='Total de Tokens')),
                ('cache_creation_tokens', models.IntegerField(default=0, help_text='Tokens usados para criar o cache (Anthropic)', verbose_name='Tokens de Criação de Cache')),
                ('cache_read_tokens', models.IntegerField(default=0, help_text='Tokens lidos do cache (Anthropic - ~90% desconto)', verbose_name='Tokens Lidos do Cache')),
                ('input_cost', models.DecimalField(decimal_places=6, default=0, help_text='Custo estimado dos tokens de entrada', max_digits=10, verbose_name='Custo de Entrada (USD)')),
                ('output_cost', models.DecimalField(decimal_places=6, default=0, help_text='Custo estimado dos tokens de saída', max_digits=10, verbose_name='Custo de Saída (USD)')),
                ('cache_creation_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Custo de Criação de Cache (USD)')),
                ('cache_read_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Custo de Leitura de Cache (USD)')),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, help_text='Soma de todos os custos', max_digits=10, verbose_name='Custo Total (USD)')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Tempo em milissegundos da chamada', null=True, verbose_name='Tempo de Resposta (ms)')),
                ('context_size', models.IntegerField(default=0, help_text='Número de caracteres do contexto adicional carregado', verbose_name='Tamanho do Contexto')),
                ('tools_used', models.JSONField(blank=True, default=list, help_text='Lista de ferramentas chamadas nesta interação', verbose_name='Ferramentas Usadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usages', to='agents.agent', verbose_name='Agente')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_usages', to='agents.conversation', verbose_name='Conversa')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usages', to='agents.message', verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Uso de LLM',
                'verbose_name_plural': 'Usos de LLM',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='agents_llmu_created_a04123_idx'), models.Index(fields=['conversation', '-created_at'], name='agents_llmu_convers_9ca107_idx'), models.Index(fields=['agent', '-created_at'], name='agents_llmu_agent_i_4585bd_idx'), models.Index(fields=['provider', 'model_name'], name='agents_llmu_provide_31ae02_idx')],
            },
        ),
    ]
