# Generated by Django 5.2.6 on 2025-11-27 20:14

from django.db import migrations


def create_langchain_tables(apps, schema_editor):
    """
    Cria as tabelas necessárias para o LangChain PGVector.

    Estas tabelas são usadas pelo LangChain para armazenar embeddings
    e fazer busca vetorial semântica.
    """
    schema_editor.execute("""
        -- Habilitar extensão pgvector se ainda não estiver habilitada
        CREATE EXTENSION IF NOT EXISTS vector;

        -- Criar tabela de coleções do LangChain
        CREATE TABLE IF NOT EXISTS langchain_pg_collection (
            uuid UUID PRIMARY KEY,
            name VARCHAR(255) UNIQUE NOT NULL,
            cmetadata JSONB
        );

        -- Criar tabela de embeddings do LangChain
        CREATE TABLE IF NOT EXISTS langchain_pg_embedding (
            id VARCHAR(255) PRIMARY KEY,
            collection_id UUID REFERENCES langchain_pg_collection(uuid) ON DELETE CASCADE,
            embedding vector(1536),
            document TEXT,
            cmetadata JSONB
        );

        -- Criar índice para busca vetorial (HNSW é mais eficiente para grandes volumes)
        CREATE INDEX IF NOT EXISTS langchain_pg_embedding_embedding_idx
            ON langchain_pg_embedding
            USING hnsw (embedding vector_cosine_ops);
    """)


def drop_langchain_tables(apps, schema_editor):
    """
    Remove as tabelas do LangChain (rollback).
    """
    schema_editor.execute("""
        DROP TABLE IF EXISTS langchain_pg_embedding CASCADE;
        DROP TABLE IF EXISTS langchain_pg_collection CASCADE;
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_langchaincollection_langchainembedding_llmusage'),
    ]

    operations = [
        migrations.RunPython(create_langchain_tables, reverse_code=drop_langchain_tables),
    ]
