# Generated by Django 5.2.6 on 2025-11-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_create_langchain_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='collection_uuid',
            field=models.UUIDField(blank=True, help_text='UUID da coleção no PGVector para os documentos deste agente', null=True, verbose_name='UUID da Coleção'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='collection_uuid',
            field=models.UUIDField(blank=True, help_text='UUID da coleção no PGVector para os documentos deste agente', null=True, verbose_name='UUID da Coleção'),
        ),
    ]
