# Generated by Django 5.2.6 on 2025-11-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_agent_collection_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentfile',
            name='usage_type',
            field=models.CharField(choices=[('context_only', 'Apenas Contexto'), ('sendable', 'Enviável ao Usuário'), ('both', 'Contexto e Enviável')], default='context_only', help_text='Define como este arquivo pode ser usado pelo agente', max_length=20, verbose_name='Tipo de Uso'),
        ),
        migrations.AddField(
            model_name='historicalagentfile',
            name='usage_type',
            field=models.CharField(choices=[('context_only', 'Apenas Contexto'), ('sendable', 'Enviável ao Usuário'), ('both', 'Contexto e Enviável')], default='context_only', help_text='Define como este arquivo pode ser usado pelo agente', max_length=20, verbose_name='Tipo de Uso'),
        ),
    ]
