# Generated by Django 5.2.6 on 2025-12-29 13:06

import common.models
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_agentfile_usage_type_historicalagentfile_usage_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='max_tokens',
            field=models.PositiveIntegerField(default=8192, verbose_name='Máximo de tokens'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='max_tokens',
            field=models.PositiveIntegerField(default=8192, verbose_name='Máximo de tokens'),
        ),
        migrations.CreateModel(
            name='HistoricalHumanInterventionRule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('description', models.CharField(help_text='Quando chamar atendente (ex: "Emissão de nota fiscal")', max_length=255, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agents.agent', verbose_name='Agente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Regra de Intervenção Humana',
                'verbose_name_plural': 'historical Regras de Intervenção Humana',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HumanInterventionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('description', models.CharField(help_text='Quando chamar atendente (ex: "Emissão de nota fiscal")', max_length=255, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_rules', to='agents.agent', verbose_name='Agente')),
            ],
            options={
                'verbose_name': 'Regra de Intervenção Humana',
                'verbose_name_plural': 'Regras de Intervenção Humana',
                'ordering': ['description'],
            },
            bases=(common.models.HistoryMixinSave, models.Model),
        ),
    ]
