# Generated by Django 5.2.6 on 2025-12-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_alter_agent_max_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humaninterventionrule',
            name='agent',
        ),
        migrations.AddField(
            model_name='agent',
            name='human_handoff_criteria',
            field=models.TextField(blank=True, help_text='Situações em que transferir para atendimento humano (uma por linha iniciando com -)', null=True, verbose_name='Critérios de Transferência Humana'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='human_handoff_criteria',
            field=models.TextField(blank=True, help_text='Situações em que transferir para atendimento humano (uma por linha iniciando com -)', null=True, verbose_name='Critérios de Transferência Humana'),
        ),
        migrations.DeleteModel(
            name='HistoricalHumanInterventionRule',
        ),
        migrations.DeleteModel(
            name='HumanInterventionRule',
        ),
    ]
