# Generated by Django 5.2.6 on 2025-10-07 08:38

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('client_type', models.CharField(choices=[('individual', 'Pessoa Física'), ('company', 'Pessoa Jurídica')], default='individual', max_length=20, verbose_name='Tipo de Cliente')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('billing_address', models.TextField(blank=True, null=True, verbose_name='Endereço de Faturamento')),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('billing_state', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('billing_zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('billing_country', models.CharField(default='BR', max_length=2, verbose_name='País')),
                ('status', models.CharField(choices=[('pending', 'Pendente de Confirmação'), ('active', 'Ativo'), ('inactive', 'Inativo'), ('suspended', 'Suspenso')], default='active', max_length=20, verbose_name='Status')),
                ('is_2fa_enabled', models.BooleanField(default=False, help_text='Quando ativo, todos os usuários deste cliente precisarão usar 2FA', verbose_name='2FA Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='core_client_email_9bd669_idx'), models.Index(fields=['status'], name='core_client_status_d6704e_idx'), models.Index(fields=['client_type'], name='core_client_client__959181_idx')],
            },
        ),
    ]
