# Generated by Django 5.2.6 on 2025-10-08 11:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome da tag (ex: VIP, Cliente, Prospect)', max_length=50, verbose_name='Nome')),
                ('color', models.CharField(default='#3B82F6', help_text='Cor em formato hexadecimal (ex: #FF5733)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato hexadecimal (ex: #FF5733)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(help_text='Cliente proprietário desta tag', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Número no formato internacional (ex: 5511999999999)', max_length=20, verbose_name='Número de Telefone')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Perfil WhatsApp')),
                ('profile_pic_url', models.URLField(blank=True, null=True, verbose_name='Foto de Perfil')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre o contato', null=True, verbose_name='Notas')),
                ('first_contact_at', models.DateTimeField(auto_now_add=True, verbose_name='Primeiro Contato')),
                ('last_contact_at', models.DateTimeField(auto_now=True, verbose_name='Último Contato')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Total de Mensagens')),
                ('is_blocked', models.BooleanField(default=False, help_text='Se bloqueado, o bot não responderá mensagens deste contato', verbose_name='Bloqueado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.client', verbose_name='Cliente')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associadas a este contato', related_name='contacts', to='core.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-last_contact_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['client', 'name'], name='core_tag_client__f0fb27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('client', 'name')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone_number'], name='core_contac_phone_n_02cc9a_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['client'], name='core_contac_client__411c12_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_blocked'], name='core_contac_is_bloc_6683c2_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_contact_at'], name='core_contac_last_co_7c9c65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('phone_number', 'client')},
        ),
    ]
