# Generated by Django 5.2.6 on 2025-10-16 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_appointment_messagetemplate_scheduledmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='client',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='client',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='contact',
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='service',
            name='client',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(help_text='Cliente', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.client')),
                ('user', models.ForeignKey(help_text='Usuário', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
        migrations.DeleteModel(
            name='ScheduledMessage',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['client'], name='core_employ_client__fe5e07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('client', 'user')},
        ),
    ]
