# Generated by Django 5.2.6 on 2025-10-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_scheduledmessage_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data')),
                ('time', models.TimeField(help_text='Hora')),
                ('scheduled_for', models.DateTimeField(help_text='Agendado para')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('contact', models.ForeignKey(help_text='Contato vinculado a este agendamento.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.contact')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['date'], name='core_appoin_date_a776ae_idx')],
            },
        ),
    ]
