# Generated by Django 5.2.6 on 2025-10-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='calendar_event_id',
            field=models.CharField(blank=True, help_text='ID do evento criado no Google Calendar', max_length=255, null=True, verbose_name='ID do Evento no Google Calendar'),
        ),
    ]
