# Generated by Django 5.2.6 on 2025-10-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appointment_calendar_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(help_text='Número no formato internacional (ex: 5511999999999)', max_length=20, unique=True, verbose_name='Número de Telefone'),
        ),
    ]
