# Generated by Django 5.2.6 on 2025-11-03 12:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_duration', models.IntegerField(choices=[(30, '30 minutos'), (60, '1 hora'), (90, '1 hora e 30 minutos'), (120, '2 horas')], default=60, help_text='Duração padrão de cada consulta em minutos', verbose_name='Tempo de Consulta (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.OneToOneField(help_text='Cliente proprietário desta configuração de agenda', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_config', to='core.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Configuração de Agenda',
                'verbose_name_plural': 'Configurações de Agenda',
            },
        ),
        migrations.CreateModel(
            name='BlockedDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Data bloqueada para atendimento', verbose_name='Data')),
                ('reason', models.CharField(blank=True, help_text='Motivo do bloqueio (ex: Feriado, Férias, etc)', max_length=255, null=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('schedule_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_days', to='core.scheduleconfig', verbose_name='Configuração de Agenda')),
            ],
            options={
                'verbose_name': 'Dia Bloqueado',
                'verbose_name_plural': 'Dias Bloqueados',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['schedule_config', 'date'], name='core_blocke_schedul_23d9f1_idx'), models.Index(fields=['date'], name='core_blocke_date_cad708_idx')],
                'unique_together': {('schedule_config', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Dia da semana (0=Segunda, 6=Domingo)', verbose_name='Dia da Semana')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, não haverá atendimento neste dia', verbose_name='Ativo')),
                ('start_time', models.TimeField(help_text='Horário de início do expediente', verbose_name='Horário de Início')),
                ('end_time', models.TimeField(help_text='Horário de término do expediente', verbose_name='Horário de Término')),
                ('lunch_start_time', models.TimeField(blank=True, help_text='Horário de início do intervalo de almoço (opcional)', null=True, verbose_name='Horário de Início do Almoço')),
                ('lunch_end_time', models.TimeField(blank=True, help_text='Horário de término do intervalo de almoço (opcional)', null=True, verbose_name='Horário de Término do Almoço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('schedule_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='core.scheduleconfig', verbose_name='Configuração de Agenda')),
            ],
            options={
                'verbose_name': 'Dia de Atendimento',
                'verbose_name_plural': 'Dias de Atendimento',
                'ordering': ['weekday'],
                'indexes': [models.Index(fields=['schedule_config', 'weekday'], name='core_workin_schedul_36a980_idx'), models.Index(fields=['is_active'], name='core_workin_is_acti_de54c7_idx')],
                'unique_together': {('schedule_config', 'weekday')},
            },
        ),
    ]
