# Generated by Django 5.2.6 on 2025-11-03 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_scheduleconfig_blockedday_workingday'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Aguardando Confirmação'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Realizado')], default='draft', help_text='Status do agendamento', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, help_text='Data', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Agendado para', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, help_text='Hora', null=True),
        ),
        migrations.CreateModel(
            name='AppointmentToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Token único para acesso público', max_length=64, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(help_text='Data e hora de expiração do link', verbose_name='Expira em')),
                ('is_used', models.BooleanField(default=False, help_text='Se o link já foi utilizado para confirmar agendamento', verbose_name='Utilizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('appointment', models.OneToOneField(help_text='Agendamento associado a este token', on_delete=django.db.models.deletion.CASCADE, related_name='token', to='core.appointment', verbose_name='Agendamento')),
            ],
            options={
                'verbose_name': 'Token de Agendamento',
                'verbose_name_plural': 'Tokens de Agendamento',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='core_appoin_token_4126a9_idx'), models.Index(fields=['expires_at'], name='core_appoin_expires_6ce337_idx')],
            },
        ),
    ]
