# Generated by Django 5.2.6 on 2025-11-03 20:23

from django.db import migrations
from datetime import time


def create_default_working_days_for_existing_configs(apps, schema_editor):
    """
    Cria WorkingDays padrão para ScheduleConfigs que já existem
    mas não têm WorkingDays configurados.
    """
    ScheduleConfig = apps.get_model('core', 'ScheduleConfig')
    WorkingDay = apps.get_model('core', 'WorkingDay')

    # Horários padrão para cada dia da semana
    default_working_hours = [
        # Segunda-feira (0)
        {
            'weekday': 0,
            'is_active': True,
            'start_time': time(8, 0),
            'end_time': time(18, 0),
            'lunch_start_time': time(12, 0),
            'lunch_end_time': time(13, 0),
        },
        # Terça-feira (1)
        {
            'weekday': 1,
            'is_active': True,
            'start_time': time(8, 0),
            'end_time': time(18, 0),
            'lunch_start_time': time(12, 0),
            'lunch_end_time': time(13, 0),
        },
        # Quarta-feira (2)
        {
            'weekday': 2,
            'is_active': True,
            'start_time': time(8, 0),
            'end_time': time(18, 0),
            'lunch_start_time': time(12, 0),
            'lunch_end_time': time(13, 0),
        },
        # Quinta-feira (3)
        {
            'weekday': 3,
            'is_active': True,
            'start_time': time(8, 0),
            'end_time': time(18, 0),
            'lunch_start_time': time(12, 0),
            'lunch_end_time': time(13, 0),
        },
        # Sexta-feira (4)
        {
            'weekday': 4,
            'is_active': True,
            'start_time': time(8, 0),
            'end_time': time(18, 0),
            'lunch_start_time': time(12, 0),
            'lunch_end_time': time(13, 0),
        },
        # Sábado (5)
        {
            'weekday': 5,
            'is_active': True,
            'start_time': time(8, 0),
            'end_time': time(12, 0),
            'lunch_start_time': None,
            'lunch_end_time': None,
        },
        # Domingo (6)
        {
            'weekday': 6,
            'is_active': False,
            'start_time': time(8, 0),
            'end_time': time(18, 0),
            'lunch_start_time': None,
            'lunch_end_time': None,
        },
    ]

    # Buscar todos os ScheduleConfigs
    configs = ScheduleConfig.objects.all()

    for config in configs:
        # Verificar se já tem WorkingDays
        existing_days_count = WorkingDay.objects.filter(schedule_config=config).count()

        if existing_days_count == 0:
            # Criar os 7 dias de atendimento padrão
            for day_config in default_working_hours:
                WorkingDay.objects.create(
                    schedule_config=config,
                    **day_config
                )
            print(f"✅ Criados 7 dias de atendimento para ScheduleConfig {config.id}")
        else:
            print(f"⏭️  ScheduleConfig {config.id} já possui {existing_days_count} WorkingDays configurados")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appointment_status_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_default_working_days_for_existing_configs,
            reverse_code=migrations.RunPython.noop
        ),
    ]
