# Generated by Django 5.2.6 on 2025-11-06 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_default_working_days_to_existing_configs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome completo do serviço (ex: Consulta Clínica Geral)', max_length=255, verbose_name='Nome do Serviço')),
                ('slug', models.SlugField(blank=True, help_text='Sigla ou código do serviço (ex: CCG)', max_length=100, verbose_name='Sigla')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do serviço', null=True, verbose_name='Descrição')),
                ('duration', models.IntegerField(help_text='Duração do serviço em minutos', verbose_name='Duração (minutos)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Valor do serviço em reais', max_digits=10, verbose_name='Valor (R$)')),
                ('service_type', models.CharField(choices=[('particular', 'Particular'), ('convenio', 'Convênio'), ('sus', 'SUS')], default='particular', help_text='Tipo de serviço', max_length=20, verbose_name='Tipo')),
                ('auto_scheduling_enabled', models.BooleanField(default=False, help_text='Permite que clientes agendem este serviço online', verbose_name='AutoAgendamento Ativo')),
                ('scheduling_link_token', models.CharField(blank=True, help_text='Token único para link público de agendamento', max_length=64, null=True, unique=True, verbose_name='Token do Link')),
                ('scarcity_enabled', models.BooleanField(default=False, help_text='Mostra mensagens de escassez (ex: "Apenas 2 vagas restantes")', verbose_name='Ativar Escassez')),
                ('show_adjacent_slots_only', models.BooleanField(default=False, help_text='Mostrar apenas horários próximos ao horário atual', verbose_name='Mostrar Apenas Horários Adjacentes')),
                ('max_daily_options', models.IntegerField(default=10, help_text='Número máximo de horários a mostrar por dia', verbose_name='Máximo de Opções por Dia')),
                ('is_active', models.BooleanField(default=True, help_text='Serviço está disponível para agendamento', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(help_text='Cliente proprietário deste serviço', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Dia da semana (0=Segunda, 6=Domingo)', verbose_name='Dia da Semana')),
                ('start_time', models.TimeField(help_text='Horário de início da disponibilidade', verbose_name='Horário de Início')),
                ('end_time', models.TimeField(help_text='Horário de término da disponibilidade', verbose_name='Horário de Término')),
                ('is_active', models.BooleanField(default=True, help_text='Período está ativo para agendamento', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Disponibilidade do Serviço',
                'verbose_name_plural': 'Disponibilidades dos Serviços',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['client', 'is_active'], name='core_servic_client__9aaa8f_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='core_servic_slug_521ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['auto_scheduling_enabled'], name='core_servic_auto_sc_9b8713_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('client', 'slug')},
        ),
        migrations.AddIndex(
            model_name='serviceavailability',
            index=models.Index(fields=['service', 'weekday'], name='core_servic_service_5f9bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceavailability',
            index=models.Index(fields=['is_active'], name='core_servic_is_acti_37577d_idx'),
        ),
    ]
