# Generated by Django 5.2.6 on 2025-10-07 08:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('preferred_language', models.CharField(choices=[('pt', 'Português'), ('en', 'English')], default='pt-br', help_text='Idioma preferido do usuário para a interface', max_length=10, verbose_name='Idioma Preferido')),
                ('email_confirmed', models.BooleanField(default=False, help_text='Indica se o usuário confirmou seu e-mail', verbose_name='E-mail Confirmado')),
                ('email_confirmation_token', models.CharField(blank=True, help_text='Token para confirmação de e-mail', max_length=100, null=True, verbose_name='Token de Confirmação')),
                ('email_confirmation_sent_at', models.DateTimeField(blank=True, help_text='Data e hora em que o e-mail de confirmação foi enviado', null=True, verbose_name='Confirmação Enviada em')),
                ('otp_secret', models.CharField(blank=True, help_text='Chave secreta individual para geração de códigos OTP', max_length=32, null=True, verbose_name='Chave Secreta OTP')),
                ('client', models.ForeignKey(blank=True, help_text='Cliente ao qual este usuário pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.client', verbose_name='Cliente')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
