# Generated by Django 5.2.6 on 2025-10-08 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_contact_tag_core_tag_client__f0fb27_idx_and_more'),
        ('whatsapp_connector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contato associado a esta sessão', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='core.contact', verbose_name='Contato'),
        ),
    ]
