# Generated by Django 5.2.6 on 2025-10-24 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_agentdocument_agentfile_conversation_and_more'),
        ('whatsapp_connector', '0002_chatsession_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutioninstance',
            name='llm_config',
            field=models.ForeignKey(blank=True, help_text='Configuração do modelo de IA para esta instância', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent', verbose_name='Configuração LLM'),
        ),
        migrations.AlterField(
            model_name='historicalevolutioninstance',
            name='llm_config',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Configuração do modelo de IA para esta instância', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agents.agent', verbose_name='Configuração LLM'),
        ),
    ]
