# Generated by Django 5.2.6 on 2025-10-24 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_delete_llmproviderconfig_and_more'),
        ('whatsapp_connector', '0003_alter_evolutioninstance_llm_config_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolutioninstance',
            old_name='llm_config',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='historicalevolutioninstance',
            old_name='llm_config',
            new_name='agent',
        ),
    ]
