# Generated by Django 5.2.6 on 2025-10-24 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_remove_longtermmemory_source_and_more'),
        ('whatsapp_connector', '0004_rename_llm_config_to_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutioninstance',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent de IA que será usado para processar as mensagens', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='historicalevolutioninstance',
            name='agent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Agent de IA que será usado para processar as mensagens', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agents.agent', verbose_name='Agent'),
        ),
    ]
