# Generated by Django 5.2.6 on 2025-11-28 01:32

import common.models
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_connector', '0006_fix_invalid_agent_references'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evolutioninstance',
            name='notification_strategy',
            field=models.CharField(choices=[('all', 'Enviar para Todos'), ('random', 'Enviar para Um Aleatório')], default='random', help_text='Define como as notificações serão enviadas: para todos os contatos ou apenas um aleatório', max_length=20, verbose_name='Estratégia de Notificação'),
        ),
        migrations.AddField(
            model_name='historicalevolutioninstance',
            name='notification_strategy',
            field=models.CharField(choices=[('all', 'Enviar para Todos'), ('random', 'Enviar para Um Aleatório')], default='random', help_text='Define como as notificações serão enviadas: para todos os contatos ou apenas um aleatório', max_length=20, verbose_name='Estratégia de Notificação'),
        ),
        migrations.CreateModel(
            name='HistoricalNotificationContact',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Nome da pessoa que receberá a notificação', max_length=100, verbose_name='Nome do Contato')),
                ('phone', models.CharField(help_text='Número no formato completo com DDI (ex: 5511999999999)', max_length=20, verbose_name='Número do WhatsApp')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, este contato não receberá notificações', verbose_name='Ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('evolution_instance', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='whatsapp_connector.evolutioninstance', verbose_name='Instância Evolution')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Contato de Notificação',
                'verbose_name_plural': 'historical Contatos de Notificação',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NotificationContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Nome da pessoa que receberá a notificação', max_length=100, verbose_name='Nome do Contato')),
                ('phone', models.CharField(help_text='Número no formato completo com DDI (ex: 5511999999999)', max_length=20, verbose_name='Número do WhatsApp')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, este contato não receberá notificações', verbose_name='Ativo')),
                ('evolution_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_contacts', to='whatsapp_connector.evolutioninstance', verbose_name='Instância Evolution')),
            ],
            options={
                'verbose_name': 'Contato de Notificação',
                'verbose_name_plural': 'Contatos de Notificação',
                'ordering': ['name'],
                'unique_together': {('evolution_instance', 'phone')},
            },
            bases=(common.models.HistoryMixinSave, models.Model),
        ),
    ]
