# Generated by Django 5.2.6 on 2025-10-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarauth',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
