# Generated by Django 5.2.6 on 2025-10-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0002_alter_googlecalendarauth_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarintegrationrequest',
            name='whatsapp_number',
            field=models.CharField(max_length=50),
        ),
    ]
